Repository IBM/CAST, pull requests merged in 2019-06, with the labels that each got.

#698 UTF8 fix
  csm_big_data/beats/utility-scripts/csmTransactionRebuild.py
Labels: Comp: CSM, Comp: CSM.bds, PhaseFound: Customer, Sev: 3, Status: Verify, Type: Defect

#709 csmdb: schema migration 18.0 updated related to csm_switch tables and…
  csmdb/sql/csm_create_tables.sql
  csmdb/sql/csm_db_migration_scripts/csm_db_schema_updates_18_0_ms.sql
  csmdb/sql/csm_db_schema_version_upgrade_18_0.sh
  docs/source/csm/csmdb/csm_db_appendix.rst
  docs/source/csm/csmdb/csm_db_appendix_table_csv_files/csm_db_fks_06_03_2019_11_47_00.csv
  docs/source/csm/csmdb/csm_db_appendix_table_csv_files/csm_db_indexes_06_03_2019_11_47_00.csv
  docs/source/csm/csmdb/csm_db_appendix_table_csv_files/csm_db_pks_06_03_2019_11_47_00.csv
  docs/source/csm/csmdb/csm_db_appendix_table_csv_files/csm_db_uks_06_03_2019_11_47_00.csv
  docs/source/csm/csmdb/csm_db_appendix_table_csv_files/csm_triggers_functions_06_03_2019_11_47_00.csv
Labels: Comp: CSM, Comp: CSM.db, Comp: CSM.fvt, PhaseFound: Development

#711 bb:Introduce additional mutex to separate transfer data verses non-tr…
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_ExtentInfo.h
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Info.h
  bb/src/BBLV_Metadata.cc
  bb/src/BBTagInfo.cc
  bb/src/BBTagInfo.h
  bb/src/BBTagInfoMap.cc
  bb/src/BBTagInfoMap.h
  bb/src/BBTagParts.cc
  bb/src/BBTagParts.h
  bb/src/BBTransferDef.cc
  bb/src/BBTransferDef.h
  bb/src/ContribIdFile.cc
  bb/src/ExtentInfo.h
  bb/src/HandleFile.cc
  bb/src/WorkID.h
  bb/src/bbinternal.h
  bb/src/bbio.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
  bb/src/bbwrkqmgr.cc
  bb/src/bbwrkqmgr.h
  bb/src/ras.json
  bb/src/xfer.cc
  bb/src/xfer.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#696 Repaired ibm-csm-bds-kibana pre.uninstall scriptlet
  csm_big_data/rpmscripts/kibana.pre.uninstall
  csm_big_data/rpmscripts/logstash.pre.uninstall
  csm_big_data/setupRPM.cmake
Labels: Comp: CSM, Comp: CSM.bds, PhaseFound: IST, Sev: 3, Status: Verify, Type: Defect

#710 Ib cable query improvements
  csmd/src/daemon/src/csmi_request_handler/CSMIIbCableQuery.cc
  csmi/include/csm_types/struct_defs/inv/csm_ib_cable_query_input.def
  csmi/include/csm_types/struct_defs/inv/type_order.def
  csmi/include/csmi_type_inv.h
  csmi/src/inv/cmd/ib_cable_query.c
  csmi/src/inv/src/csmi_ib_cable_query.c
  csmi/src/inv/src/csmi_inv_internal.c
  csmi/src/inv/src/csmi_inv_python.cc
Labels: Comp: CSM, Comp: CSM.api, PhaseFound: IST, Sev: 3, Status: Verify, Type: Test Case Request

#717 update to use standard guid for csm mellanox
  csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
Labels: Comp: CSM, Comp: CSM.api, Comp: CSM.inventory, Comp: Mellanox, PhaseFound: Development, Sev: 3, Status: Verify

#725 dev dlherms2
  bb/src/BBLV_Info.cc
  bb/src/BBTagParts.cc
  bb/src/bbserver.cc
  bb/src/xfer.cc
  bb/src/xfer.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#688 Reducing number of json files #679
  csm_big_data/beats/config/filebeat.yml
  csmdb/sql/csm_db_history_archive.py
  csmdb/sql/csm_db_rollup.py
Labels: Comp: CSM.bds, Comp: CSM.db, PhaseFound: Customer, Sev: 2, Status: Verify, Type: Defect

#730 dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_Info.cc
  bb/src/HandleFile.cc
  bb/src/bbio.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
  bb/src/bbwrkqmgr.cc
  bb/src/bbwrkqmgr.h
  bb/src/ras.json
  bb/src/xfer.cc
  bb/src/xfer.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#732 bb:Additional transfer queue lock changes
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
  bb/src/bbwrkqmgr.cc
  bb/src/xfer.cc
  bb/src/xfer.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#733 bb:Additional verification of lock state(s) at the beginning of a dis…
  bb/src/HandleFile.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqmgr.cc
  bb/src/ras.json
  bb/src/xfer.cc
  bb/src/xfer.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#735 bb:Additional HP transfer queue lock changes
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqmgr.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#739 Dev dlherms2
  bb/src/BBLV_Info.cc
  bb/src/BBTransferDef.cc
  bb/src/HandleFile.cc
  bb/src/bbinternal.h
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
  bb/src/bbwrkqmgr.cc
  bb/src/bbwrkqmgr.h
  bb/src/ras.json
  bb/src/xfer.cc
  bb/src/xfer.h
  bb/wrappers/Procedures.py
  bb/wrappers/bbapiAdminProcs.py
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#740 Dev dlherms2
  bb/src/BBLV_Metadata.cc
  bb/src/BBLV_Metadata.h
  bb/src/bbwrkqmgr.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#741 bb:Additional lock changes
  bb/src/bbinternal.h
  bb/src/bbserver.cc
  bb/src/bbwrkqmgr.cc
  bb/src/bbwrkqmgr.h
  bb/src/xfer.cc
  bb/src/xfer.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#742 bb:Restart changes related to the changes in lock strategy
  bb/src/BBLV_Info.cc
  bb/src/BBTagInfo.cc
  bb/src/WorkID.h
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqmgr.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#743 bb:Additional lock changes for restart processing
  bb/scripts/bb.cfg.in
  bb/src/bbwrkqmgr.cc
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#744 Dev dlherms2
  bb/src/bbcmd.cc
  bb/src/bbinternal.h
  bb/src/bbproxy.cc
  bb/src/bbproxy.h
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect
