Repository IBM/CAST, pull requests merged in 2019-07, with the labels that each got.

#747 bb: Additional restart changes
  bb/src/BBLV_Metadata.cc
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#750 dev dlherms2
  bb/src/BBLV_Metadata.cc
  bb/src/BBTagInfo.cc
  bb/src/BBTagInfoMap.cc
  bb/src/LVUtils.cc
  bb/src/bbproxy.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqmgr.cc
  bb/src/fh.cc
  bb/src/fh.h
  bb/src/lvlookup.cc
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#752 Dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_ExtentInfo.h
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Info.h
  bb/src/BBLV_Metadata.cc
  bb/src/BBTagInfo.cc
  bb/src/BBTagInfoMap.cc
  bb/src/HandleFile.cc
  bb/src/bbproxy.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
  bb/src/bbwrkqmgr.cc
  bb/src/bbwrkqmgr.h
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#721 csm_fvt: new case related to error inject timeout #658 #665
  csmtest/buckets/error_injection/timeout.sh
Labels: Comp: CSM, Comp: CSM.fvt, Comp: CSM.infra, Type: Test Case Added

#754 Dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_ExtentInfo.h
  bb/src/BBLV_Info.cc
  bb/src/BBTagParts.cc
  bb/src/bbinternal.h
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqmgr.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#756 dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Info.h
  bb/src/BBLV_Metadata.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqmgr.cc
  bb/src/ras.json
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#761 Dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_ExtentInfo.h
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Metadata.cc
  bb/src/BBTagInfo.cc
  bb/src/BBTransferDef.cc
  bb/src/BBTransferDef.h
  bb/src/ContribIdFile.cc
  bb/src/HandleFile.cc
  bb/src/LVUtils.cc
  bb/src/LVUuidFile.cc
  bb/src/bbinternal.h
  bb/src/bbio.cc
  bb/src/bbproxy.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqmgr.cc
  bb/src/main.cc
  bb/src/xfer.cc
  bb/src/xfer.h
  bb/wrappers/bbapi.py
  transport/scripts/txpConfig.py
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#759 CSM Allocation Multiple Allocation fix
  csmd/src/daemon/src/csmi_request_handler/CSMIAllocationQuery.cc
  csmi/include/csm_api_version.h
  csmi/include/csm_types/struct_defs/wm/csmi_allocation.def
  csmi/include/csm_types/struct_defs/wm/special_preprocess.def
  csmi/include/csm_types/struct_defs/wm/type_order.def
  csmi/include/csmi_type_bb.h
  csmi/include/csmi_type_diag.h
  csmi/include/csmi_type_inv.h
  csmi/include/csmi_type_ras.h
  csmi/include/csmi_type_wm.h
  csmi/include/struct_generator/generate_struct.pl
  csmi/src/bb/include/csmi_bb_type_internal.h
  csmi/src/common/include/csmi_common_type_internal.h
  csmi/src/wm/cmd/allocation_query.c
  csmi/src/wm/include/csmi_wm_type_internal.h
  csmi/src/wm/src/csmi_wm_internal.c
  csmi/src/wm/src/csmi_wm_python.cc
  csmtest/buckets/error_injection/allocation.sh
Labels: Comp: CSM.api, PhaseFound: Customer, PhaseFound: Development, Sev: 2, Status: Verify, Type: Defect

#768 dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Metadata.cc
  bb/src/Extent.h
  bb/src/bbserver.cc
  bb/src/bbwrkqe.cc
  bb/src/bbwrkqe.h
  bb/src/bbwrkqmgr.cc
  bb/src/bbwrkqmgr.h
  bb/src/ras.json
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#772 Dev dlherms2
  bb/src/BBTransferDef.cc
  bb/src/bbwrkqe.cc
  bb/src/connections.cc
  transport/scripts/txpConfig.py
  transport/scripts/txpParser.py
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#773 Dev dlherms2
  bb/src/BBLV_Metadata.cc
  bb/src/bbserver.cc
  bb/wrappers/bbtests.py
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 3, Status: Pending in Pull Request, Type: Defect

#767 added test case regarding #759 and #760
  csmtest/buckets/error_injection/allocation.sh
Labels: Comp: CSM.fvt, Sev: 3, Status: Verify, Type: Test Case Added
