Repository IBM/CAST, pull requests merged in 2019-10, with the labels that each got.

#796 Dev dlherms2
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Info.h
  bb/src/bbapi.cc
  bb/src/bbapi2.cc
  bb/src/bbapi2.h
  bb/src/bbinternal.h
  bb/src/bbwrkqe.cc
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#797 bb:Revert to prior CRuntime check in BB_InitLibrary()
  bb/src/bbapi.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#799 bb:For removejobinfo processing while those transfers are being proce…
  bb/src/BBLV_Info.cc
  bb/src/BBLV_Info.h
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#800 bb:Remove validation of UNDEFINED_JOBSTEPID for gettransferlist. Red…
  bb/src/bbproxy.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#801 bb:In tools/scripts, process stagein and stageout logs
  bb/tools/scripts/analyze.py
  bb/tools/scripts/common.py
  bb/tools/scripts/processConsoleLogs.py
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 3, Status: Pending in Pull Request, Type: Defect

#793 Issues/770 csm allocation step query details segmentation fault
  csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepQueryDetails.cc
  csmi/src/wm/cmd/allocation_step_query_details.c
  csmtest/buckets/basic/step.sh
Labels: Comp: CSM, Comp: CSM.api, PhaseFound: Development, Sev: 2, Status: Verify, Type: Defect

#807 bb:Modify TagFile processing to first look for the tag, expectContrib…
  bb/src/BBTagInfo.cc
  bb/src/TagFile.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#809 Dev dlherms2
  bb/src/BBTagInfoMap.cc
  bb/src/HandleFile.cc
  bb/src/TagFile.cc
  bb/src/TagFile.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect
