Repository IBM/CAST, pull requests merged in 2019-11, with the labels that each got.

#810 bb:When searching for existing handles, use multiple taginfo/handlein…
  bb/src/BBTagInfo.cc
  bb/src/BBTagInfoMap.cc
  bb/src/CMakeLists.txt
  bb/src/HandleInfo.cc
  bb/src/HandleInfo.h
  bb/src/TagInfo.cc
  bb/src/TagInfo.h
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#811 fvt enhancements related to csm_install.sh script (nvidia-persistence…
  csmtest/setup/csm_install.sh
Labels: Comp: CSM.fvt, PhaseFound: FVT, Status: Verify, Type: New Feature

#814 Dev dlherms2
  bb/src/BBLV_ExtentInfo.cc
  bb/src/BBLV_Metadata.cc
  bb/src/BBTagInfo.cc
  bb/src/BBTagInfoMap.cc
  bb/src/BBTransferDef.cc
  bb/src/ContribIdFile.cc
  bb/src/HandleFile.cc
  bb/src/HandleFile.h
  bb/src/HandleInfo.h
  bb/src/LVUuidFile.cc
  bb/src/TagInfo.cc
  bb/src/TagInfo.h
  bb/src/bbinternal.h
  bb/src/bbio_regular.cc
  bb/src/bbserver.cc
  bb/src/bbwrkqmgr.cc
  bb/src/xfer.cc
Labels: Comp: Burst Buffer, PhaseFound: Customer, Sev: 2, Status: Pending in Pull Request, Type: Defect

#818 Csm elk 6 8 1 compatibility
  csm_big_data/beats/config/filebeat.yml
  csm_big_data/logstash/patches/csm_logstash_6-8-1_patch.sh
Labels: Comp: CSM, Comp: CSM.bds, PhaseFound: Development, Sev: 3

#820 bb:Fix race condition when creating/obtaining a handle for the very s…
  bb/src/bbserver.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#822 bb:Altered the fix for the getHandle race condition above
  bb/src/BBTagInfoMap.cc
  bb/src/TagInfo.cc
  bb/src/TagInfo.h
  bb/src/bbserver.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#824 bb:Minor performance changes for getHandle
  bb/src/TagInfo.cc
Labels: Comp: Burst Buffer, PhaseFound: Development, Sev: 2, Status: Pending in Pull Request, Type: Defect

#825 Set next release to 1.8.0 in master branch
  CMakeLists.txt
Labels: Comp: Build

#827 csm fvt script updates - added big data rpm lines to install and uni…
  csmtest/setup/csm_install.sh
  csmtest/setup/csm_uninstall.sh
Labels: Comp: CSM, Comp: CSM.fvt, PhaseFound: Build, PhaseFound: FVT
